### ISSUE TITLE
Picaboooo.com reliability

### ISSUE THREAD

**Issue by ghost** [Picaboooo/SnapchatSDK#1]
I'm working on a project that uses this API and can't really be dependent on an external domain to sign the requests for authorization.

Also doesn't make sense as if/when the picaboooo.com domain expires / shuts down, this package will stop working entirely. 

If there are any privacy-sensitive reasons that you wish to not comment on this issue publicly, please email me at [ EMAIL REDACTED DUE TO UNRELATED PEOPLE EMAILING ME ]

The project is able to be monetized and I could give you a percentage of all the subscription costs in exchange for the picaboooo.com auth service. Please consider.

Thanks!

**Comment by Picaboooo** [comment]
I've sent you an email.

**Comment by spartanz51** [comment]
Hello, may i receive information about that please?
Thanks

spartanz51 [at] live [dot] fr
