### ISSUE TITLE
Snap map integration? 

### ISSUE THREAD

**Issue by jamesthejellyfish** [Picaboooo/SnapchatSDK#10]
I can't seem to find any mention of snap map integration. Is it already implemented and I didn't see it, or is such a thing impossible? I really appreciate the api as the previous Casper-based one is no longer available, with snap map integration being my only issue with it as it stands.

**Comment by ghost** [comment]
Technically, AFAIK if the casper API has that part open-source you could 
just transfer the exact same code into a new class file or wait for a 
pull request.

**Comment by shkumbinhasani** [comment]
@acvigue do you still have the casper API i cant find it anywhere
