### ISSUE TITLE
Sending snaps to multiple recipients?

### ISSUE THREAD

**Issue by mememan840** [Picaboooo/SnapchatSDK#11]
I've tried adding a comma but it didn't seem to work, is this possible?

**Comment by shkumbinhasani** [comment]
it is working snapchat allows only up to 200

**Comment by mememan840** [comment]
So it'd be like this?

    $snapchat->sendMedia($uploadPayload, 10, ["1", "2", "3"])

etc?
;

**Comment by shkumbinhasani** [comment]
yes

**Comment by mememan840** [comment]
Thank you!

**Comment by mememan840** [comment]
Do you also know a way to remove friends trough the API?

**Comment by mememan840** [comment]
nvm got it
