### ISSUE TITLE
Business enquiry

### ISSUE THREAD

**Issue by fhsk739hfej** [Picaboooo/SnapchatSDK#13]
Hello,

I'd like to get in contact with you in order to talk about this repo.
I have some offers for you, that you would probably appreciate.
The only contact method I found is by creating an issue there, so I hope that's ok.
Please, email me: [fhsk739hfej[at]gmail[dot]com](mailto:fhsk739hfej@gmail.com), I will be replying as fast as possible.

Regards.

**Comment by Picaboooo** [comment]
picaboooo@protonmail.com
