### ISSUE TITLE
[BUG] Verified Accounts can't logn

### ISSUE THREAD

**Issue by MiniFix** [Picaboooo/SnapchatSDK#2]
Hello,

Thanks for the project. There is a bug where it don't let you login if your account has been verified. If you try with a new non-verified account it works fine but this is what happens when you try login with a verified account:

On the new version where you added 2FA Support (Thanks for that!) it will show this message when tring to login and send a snap: `"You must be logged in to call uploadMedia()"`

But on the old version 1.0 before 2FA Support it shows this error:

`PHP Fatal error:  Uncaught Error: Call to a member function getUsername() on null in /vendor/picaboooo/snapchatsdk/src/Snapchat/SnapchatClient.php:248
Stack trace:
#0 /vendor/picaboooo/snapchatsdk/examples/example.loginAndSendSnap.php(16): Snapchat\SnapchatClient->login('UserName', 'Password')
#1 {main}
  thrown in /vendor/picaboooo/snapchatsdk/src/Snapchat/SnapchatClient.php on line 248
`

We don't get sent the AuthToken either.

So basicly once Snapchat send you the verification email for your account if you click on the link in your email then your account is verified and you can no longer login with this script.

Please if you could look into it we would be greatful. Thanks for your time in this project!

**Comment by Picaboooo** [comment]
Verified account meaning? Do you mean having a verified email or did you enable 2FA SMS / APP?
I need to be able to reproduce this to fix it. Maybe show some code if possible?

When Snapchat sends me a verification email, it's not a link but a token.

**Comment by MiniFix** [comment]
I don't mean 2FA. If you create a new Snapchat Account and use your examples it works. But if i go into the Snapchat App and go to the settings for my account, my email will show up as red as i have not verified it yet for my account so i click on it and tell the app to send me a verification email for my new account , i get the email i click on it but now your script no longer works. I tried it with the `example.loginAndSendSnap.php` example and it gives the errors above. But if i don't verify my account it works just fine.

I created 4 accounts i left 2 of them not verified works. I verifed 2 of them by email (Link the email to the account) and now it don't work on them 2 accounts.

If you don't have any verfied accounts i can make one and give you the login to test.

I am not talking about 2FA Verification it's the verification that links your email to your Snapchat account. 

Thanks for any help.

**Comment by Picaboooo** [comment]
It's possible that you need to verify the identity if Snapchat thinks your login is suspicious. Save the result of `login` in a variable, then check `$login->isTwoFaNeeded()` and `$login->isOdlvRequired()`.

You should always check this after login.

**Comment by MiniFix** [comment]
Ahhhhhh yessss sorry i forgot all about that it's working now. I downloaded your new version with 2FA support but i forgot to actually look at the login_2fa PHP file on how to use it. Instead i was still using the old login method. Oops.

My bad but i did just find a bug in login_2fa.php you forgot to add the require code and it fails to load unless added.
`require_once __DIR__ . '/../vendor/autoload.php';`

Thanks for your help! I was looking to make a service like this but i don't have the time anymore lol but good job!

**Comment by Picaboooo** [comment]
Good to hear and thanks for the bug report, I fixed the example.
