### ISSUE TITLE
Cant login "INTERNAL SERVER ERROR"

### ISSUE THREAD

**Issue by ixSly** [Picaboooo/SnapchatSDK#4]
So it appears that the server returns a 500 error while logging in .

**Comment by krjan02** [comment]
same...
```
Server error: POST https://picaboooo.com/v1/login resulted in a 500 INTERNAL SERVER ERROR response
```

**Comment by ZamasuTheGod** [comment]
**Yes same here! Please fix it brother we luv your work!**

**Comment by ghost** [comment]
Sent you an email, @Picaboooo. Please fix or think about my previous emails. My customers can't link accounts.

**Comment by Picaboooo** [comment]
Looking into this..

**Comment by Picaboooo** [comment]
Fixed, sorry for the issue.

**Comment by ghost** [comment]
Confirmed fixed, thank you for quick reply!

**Comment by bufferbandit** [comment]
Wow, first of all, thank you so much for this quick fix. I really appreciate the incredible work you've done by making this project possible. I only have one question: what is the role of the picaboooo.com domain in this package, and what data does it process?

Is there any way I could get in contact with you? I am really excited to understand more about how this works. I am really looking forward to your response. My email address is: bufferbandit@mbox.re

Hope to hear from you soon.

**Comment by bufferbandit** [comment]
Wow, first of all, thank you so much for this quick fix. I really appreciate the incredible work you've done by making this project possible. I only have one question: what is the role of the picaboooo.com domain in this package, and what data does it process?

Is there any way I could get in contact with you? I am really excited to understand more about how this works. I am really looking forward to your response. My email address is: bufferbandit@mbox.re

Hope to hear fro you soon.

**Comment by ghost** [comment]
AFAIK from his emails, it's just a simple web app that generates the tokens that Snapchat expects.
edit: you sent twice

**Comment by bufferbandit** [comment]
Hey @acvingue, thank y LJ nou for your quifk response as well!

Altho I don't understand why the tokens have to be generated on the server. Is there a reason this can not happen locally?

**Comment by bufferbandit** [comment]
Hey @acvingue, thank your quick response as well!

Although I don't understand why the tokens have to be generated on the server. Is there a reason this can not happen locally?

**Comment by ixSly** [comment]
Can you please clear to me how these headers being generated ? I am interested as I have a project to work thats going to be launched soon,  I could give you a percentage of all the subscription costs in exchange for your API's service .

Contact me at e44@hotmail.com.
