### ISSUE TITLE
Contact You?

### ISSUE THREAD

**Issue by 0day-zzz** [Picaboooo/SnapchatSDK#6]
Hi, 

Is there any way I can contact you directly? I have some questions and a potential business proposal.

Thanks.

**Comment by 0day-zzz** [comment]
my email is jake@bolam.pw

Please contact me! 

It is regarding the server side auth token generation.

**Comment by acvigue** [comment]
@0day Please don’t email me. Thank you in advance. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by manu120189** [comment]
Hi! I would like to know more about the server side auth tokens also, is there a way we can have access to that code? thanks great work btw.

**Comment by Picaboooo** [comment]
@manu120189 No.
picaboooo@protonmail.com
